namespace: paysafe

replicaCount: 2

backend:
  image:
    repository: aslahea/paysafe-backend
    tag: v1
  service:
    port: 5000

frontend:
  image:
    repository: aslahea/paysafe-frontend
    tag: v1
  service:
    port: 80

istio:
  host: paysafe.local

deploymentStrategy: canary 