apiVersion: apps/v1
kind: Deployment
metadata:
  name: paysafe-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: paysafe-backend
  template:
    metadata:
      labels:
        app: paysafe-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 5000