{{- if eq .Values.deploymentStrategy "bluegreen" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: paysafe-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paysafe-backend
  strategy:
    blueGreen:
      activeService: paysafe-backend-active
      previewService: paysafe-backend-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: paysafe-backend
    spec:
      containers:
      - name: backend
        image: "aslahea/paysafe-backend:{{ .Values.backend.image.tag }}"
        env:
        - name: APP_VERSION
          value: {{ .Values.backend.image.tag | quote }}
{{- end }}
