{{- if eq .Values.deploymentStrategy "canary" }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: paysafe-backend
  namespace: {{ .Values.namespace }}
spec:
  host: paysafe-backend
{{- end }}
